(function(){
  const guides=[
    {cat:"Élèves",icon:"👤",title:"Ajouter ou créer un élève",summary:"Depuis le répertoire ou pendant la création d’une classe",go:"students",steps:["Ouvrez Élèves pour accéder au répertoire général.","Utilisez Ajouter un élève, puis renseignez son identité, sa classe et ses coordonnées.","Enregistrez. Sa fiche pourra ensuite être utilisée dans les classes, dispenses, évaluations et l’AS."],note:"Pour ajouter beaucoup d’élèves, créez une classe puis importez le fichier CSV de l’établissement."},
    {cat:"Élèves",icon:"✏️",title:"Modifier ou supprimer une fiche élève",summary:"Corriger une identité, un e-mail ou retirer une fiche",go:"students",steps:["Ouvrez Élèves et recherchez le nom.","Ouvrez la fiche puis choisissez Modifier pour corriger les informations.","Utilisez Supprimer uniquement si la fiche entière ne doit plus exister."],note:"Supprimer une fiche n’est pas la même chose que retirer un élève d’une classe."},
    {cat:"Classes",icon:"🏫",title:"Créer une classe et importer les élèves",summary:"Création vide ou import CSV",go:"classes",steps:["Ouvrez Classe, puis Créer une classe.","Choisissez le niveau, le numéro et l’année scolaire.","Ajoutez éventuellement un fichier CSV et vérifiez l’aperçu.","Cliquez sur Créer la classe. Vous pourrez compléter les élèves ensuite."]},
    {cat:"Classes",icon:"↪",title:"Retirer un élève d’une classe",summary:"Depuis le menu Actions de sa ligne",go:"classes",steps:["Ouvrez Classe, puis Mes classes.","Entrez dans la classe concernée et ouvrez la liste des élèves.","À droite du niveau EPS, ouvrez Actions.","Choisissez Retirer de cette classe et confirmez."],note:"L’élève disparaît de la liste active ; ses résultats et son historique ne sont pas effacés physiquement."},
    {cat:"Classes",icon:"📝",title:"Créer une évaluation",summary:"Critères, barème, notes et export",go:"classes",steps:["Ouvrez la classe puis Évaluations / Tests.","Créez une évaluation, donnez-lui un nom et choisissez la période.","Ajoutez les critères et le nombre de points de chacun.","Saisissez les résultats en colonnes, puis enregistrez.","Rouvrez l’évaluation pour la modifier ou l’exporter en PDF/Excel."]},
    {cat:"Santé",icon:"🩹",title:"Créer une dispense",summary:"Dates, motif et activité adaptée",go:"health",steps:["Ouvrez Santé / Accident puis Dispense.","Choisissez la classe et l’élève dans les listes.","Indiquez les dates, le motif et, si nécessaire, les activités adaptées.","Enregistrez. La dispense apparaît dans Mes dispensés et Tous les dispensés."],note:"Une dispense saisie par l’infirmerie apparaît également dans Tous les dispensés des professeurs autorisés."},
    {cat:"Santé",icon:"⚕️",title:"Rédiger un rapport d’incident",summary:"Élève, témoins, circonstances et conservation",go:"health",steps:["Ouvrez Santé / Accident puis Accident.","Sélectionnez l’élève et complétez chaque étape du rapport.","Pour les témoins, choisissez un élève dans la liste ou utilisez le choix libre.","Vérifiez le récapitulatif, enregistrez puis imprimez si nécessaire."]},
    {cat:"ASLVH",icon:"🏆",title:"Ajouter et licencier un élève à l’AS",summary:"Créer une fiche licencié",go:"unss",steps:["Ouvrez ASLVH puis Licenciés AS.","Cliquez sur Ajouter et recherchez d’abord l’élève dans le répertoire.","Complétez les informations manquantes et activez la licence.","Enregistrez la fiche."]},
    {cat:"ASLVH",icon:"➖",title:"Retirer une licence AS",summary:"Conserver l’élève mais le retirer des licenciés",go:"unss",steps:["Ouvrez ASLVH puis Licenciés AS.","Ouvrez la fiche de l’élève.","Cliquez sur Retirer la licence AS et confirmez."],note:"La fiche de l’élève reste dans le répertoire ; seule sa licence AS est retirée."},
    {cat:"ASLVH",icon:"🕒",title:"Créer un créneau AS",summary:"Activité, horaires, lieu et responsable",go:"unss",steps:["Ouvrez ASLVH puis Créneaux AS.","Cliquez sur Ajouter un créneau.","Renseignez l’activité, le jour, les horaires, le lieu et le professeur responsable.","Enregistrez puis ouvrez le créneau pour ajouter les élèves.","Le bouton Télécharger édite la liste des créneaux avec les professeurs rattachés."]},
    {cat:"ASLVH",icon:"🚌",title:"Créer et remplir une sortie / date AS",summary:"Participants, accompagnateurs, transport et besoins",go:"unss",steps:["Ouvrez ASLVH puis Dates AS.","Créez une nouvelle date et renseignez l’événement et l’activité.","Choisissez les professeurs accompagnants et les élèves participants.","Complétez le lieu, le déplacement, les horaires et les besoins.","Enregistrez la fiche ; vous pourrez la rouvrir et télécharger la liste des élèves."]},
    {cat:"ASLVH",icon:"✅",title:"Faire l’appel AS",summary:"Présences, historique et mail aux absents",go:"unss",steps:["Ouvrez ASLVH puis Appel AS.","Choisissez le créneau et la date.","Pointez les présents et les absents, puis enregistrez.","Dans l’historique, ouvrez Actions pour modifier l’appel ou préparer le mail aux absents."]},
    {cat:"Messages",icon:"✉️",title:"Envoyer un mail depuis l’AS",summary:"Confirmation, message libre et petits lots",go:"unss",steps:["Dans Réglage, connectez d’abord Gmail professionnel.","Dans ASLVH, choisissez les destinataires ou ouvrez un créneau puis Envoyer un e-mail.","Choisissez Confirmation d’inscription ou Message libre.","Créez d’abord un brouillon test et envoyez-le depuis Gmail.","Préparez ensuite de petits lots et surveillez les retours mailer-daemon."],note:"Si Gmail professionnel n’est pas connecté, l’ancien mode d’envoi reste disponible."},
    {cat:"Outils",icon:"⏱️",title:"Utiliser un outil individuel",summary:"Chrono, test, observation et résultats par élève",go:"outils",steps:["Ouvrez Outils et choisissez l’activité ou Tous.","Sélectionnez l’outil : chrono, test ou observation.","Choisissez une classe et la période, puis saisissez les résultats.","Enregistrez avec un nom pour retrouver le travail plus tard.","Utilisez Exporter pour produire un PDF ou un fichier Excel lorsque proposé."]},
    {cat:"Outils",icon:"👥",title:"Utiliser un outil collectif",summary:"Scores, tournois, rotations et groupes",go:"outils",steps:["Ouvrez Outils puis Sports collectifs, Raquettes ou Tous.","Choisissez Scores, Tournoi, Rotations ou Équipes.","Sélectionnez la classe et constituez les groupes.","Enregistrez la composition si vous souhaitez la réutiliser.","Les résultats et évaluations restent rangés dans Tests / Évaluations, pas dans la composition d’équipe."]},
    {cat:"Outils",icon:"🧗",title:"Faire le test spécial escalade",summary:"Progression, difficulté, technique et assurage sur 20",go:"outils",steps:["Ouvrez Outils puis Escalade et Tests.","Choisissez une classe et une période.","Pour chaque élève, indiquez la progression dans la voie puis sa difficulté.","Notez la technique de grimpe sur 5 et l’assurage sur 5.","Enregistrez : les élèves restent en lignes et les critères en colonnes."]},
    {cat:"Outils",icon:"⭐",title:"Mettre un outil en favori",summary:"Retrouver l’outil directement sur l’accueil",go:"outils",steps:["Ouvrez Outils.","Cliquez sur l’étoile de la carte de l’outil.","Le premier favori apparaît dans la carte Outils de l’accueil.","Cliquez de nouveau sur l’étoile pour le retirer des favoris."]},
    {cat:"Cours",icon:"📚",title:"Créer un cycle et préparer les séances",summary:"Activité, niveau, objectifs et déroulement",go:"cours",steps:["Ouvrez Cours puis Cycle.","Créez le cycle, choisissez la classe, l’activité et la période.","Ajoutez ou adaptez les séances proposées.","Dans Cours, ouvrez la séance du jour et utilisez le mode cours en plein écran."]},
    {cat:"Planning",icon:"📅",title:"Construire le planning et la programmation",summary:"Créneaux hebdomadaires, périodes et installations",go:"programmation",steps:["Ouvrez Planning pour placer les cours hebdomadaires.","Choisissez la classe, le jour, l’horaire et l’installation.","Ouvrez Programmation pour répartir les activités par période.","Utilisez Référentiel BAC EPS pour consulter directement les documents officiels."]},
    {cat:"Équipement",icon:"🏋️",title:"Gérer le matériel et les EPI",summary:"Stock, contrôles, achats et suivi",go:"equipement",steps:["Ouvrez Équipement puis Matériel ou EPI.","Ajoutez l’équipement et ses informations utiles.","Enregistrez les inspections, achats ou changements d’état.","Utilisez les filtres pour retrouver les éléments à contrôler."]},
    {cat:"Équipement",icon:"⚠️",title:"Signaler un problème d’installation",summary:"Installation, description, WhatsApp et suivi",go:"equipement",steps:["Ouvrez Équipement puis Installations sportives.","Ouvrez l’installation et choisissez Signaler un incident.","Décrivez précisément le problème.","Préparez le message WhatsApp destiné au responsable unique.","Suivez ensuite le signalement et indiquez En cours ou Résolu."]},
    {cat:"Données",icon:"⇩",title:"Télécharger des listes et résultats",summary:"PDF, Excel et informations des élèves",go:"classes",steps:["Ouvrez la rubrique concernée : classe, créneau AS, date AS, test ou évaluation.","Cliquez sur Télécharger, Exporter, PDF ou Excel.","Choisissez le format proposé puis enregistrez le fichier."],note:"Les exports d’élèves et de créneaux incluent les adresses e-mail lorsqu’elles sont renseignées."},
    {cat:"Données",icon:"☁️",title:"Comprendre la synchronisation et le hors connexion",summary:"Site, PWA, appareils et conflits",go:"settings",steps:["Les modifications sont d’abord conservées sur l’appareil, puis envoyées au serveur.","Dans Réglage, ouvrez Compte web / synchronisation pour vérifier l’état.","Si deux appareils modifient des champs différents, ils sont fusionnés automatiquement.","Si le même champ change des deux côtés, choisissez la version à conserver.","Les anciennes versions restent récupérables dans Réglage."],note:"Fermez simplement la PWA sans vous déconnecter pour continuer hors connexion."},
    {cat:"Réglages",icon:"⚙️",title:"Régler le profil, Gmail, les périodes et la météo",summary:"Tous les paramètres du compte",go:"settings",steps:["Ouvrez Réglage dans le menu principal.","Dépliez la section souhaitée : Profil, Gmail professionnel, Synchronisation, Périodes ou Météo.","Modifiez les informations puis utilisez le bouton Enregistrer de la section."]},
    {cat:"Réglages",icon:"🔎",title:"Retrouver rapidement une information",summary:"Recherche globale et centre d’aide",go:"home",steps:["Utilisez Rechercher en haut de l’écran pour trouver un élève, une classe ou un équipement.","Utilisez l’onglet ? Aide pour rechercher une procédure.","Tapez quelques mots simples, par exemple : mail, dispense, équipe, supprimer ou hors connexion."]}
  ];
  let active="Tout",ready=false;
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const norm=v=>String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
  function draw(){
    const q=norm(document.getElementById("helpSearch")?.value),host=document.getElementById("helpResults");if(!host)return;
    const rows=guides.filter(g=>(active==="Tout"||g.cat===active)&&(!q||norm([g.cat,g.title,g.summary,...g.steps,g.note].join(" ")).includes(q)));
    host.innerHTML=rows.length?rows.map((g,i)=>`<details class="helpTopic" data-help-index="${guides.indexOf(g)}"><summary><i>${g.icon}</i><span><b>${esc(g.title)}</b><small>${esc(g.cat)} · ${esc(g.summary)}</small></span></summary><div class="helpTopicBody"><ol>${g.steps.map(s=>`<li>${esc(s)}</li>`).join("")}</ol>${g.note?`<p class="helpNote">💡 ${esc(g.note)}</p>`:""}<button type="button" data-help-go="${g.go}">Ouvrir ${g.go==="unss"?"ASLVH":g.go==="health"?"Santé / Accident":g.go==="settings"?"Réglage":g.go==="students"?"Élèves":g.go==="classes"?"Classe":g.go==="outils"?"Outils":g.go==="equipement"?"Équipement":g.go==="programmation"?"Programmation":g.go==="cours"?"Cours":"l’accueil"}</button></div></details>`).join(""):`<div class="helpEmpty"><b>Aucun guide trouvé</b>Essayez un autre mot, par exemple « élève », « mail » ou « dispense ».</div>`;
    host.querySelectorAll("[data-help-go]").forEach(b=>b.onclick=()=>showTab(b.dataset.helpGo));
  }
  function init(){
    const filters=document.getElementById("helpFilters"),search=document.getElementById("helpSearch"),clear=document.getElementById("helpClear");if(!filters||!search)return;
    if(!ready){
      const cats=["Tout",...new Set(guides.map(g=>g.cat))];filters.innerHTML=cats.map(c=>`<button type="button" data-help-filter="${esc(c)}" class="${c==="Tout"?"active":""}">${esc(c)}</button>`).join("");
      filters.onclick=e=>{const b=e.target.closest("[data-help-filter]");if(!b)return;active=b.dataset.helpFilter;filters.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===b));draw()};
      search.oninput=()=>{clear.hidden=!search.value;draw()};clear.onclick=()=>{search.value="";clear.hidden=true;search.focus();draw()};ready=true;
    }
    draw();setTimeout(()=>search.focus(),50);
  }
  globalThis.initHelpTab=init;
})();
