let healthMode='dispense',healthClasses=[],healthStudents=[],healthDispenses=[],healthSelectedClassId=null,healthSelectedStudentId=null;
const healthEsc=value=>String(value??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const healthToday=()=>new Date().toISOString().slice(0,10);
function healthActive(row){const today=healthToday();return row.start_date<=today&&row.end_date>=today;}
async function healthFetch(path){const response=await apiFetch(`${SUPABASE_URL}/rest/v1/${path}`);return response.ok?response.json():[];}
async function initHealthTab(preselectedClassId=null){
  if(preselectedClassId)healthSelectedClassId=preselectedClassId;
  const host=document.getElementById('healthBody');if(!host)return;
  host.innerHTML='<div class="card muted">Chargement des données de santé…</div>';
  [healthClasses,healthStudents,healthDispenses]=await Promise.all([
    healthFetch('classes?deleted=eq.false&select=*&order=name'),
    healthFetch('students?deleted=eq.false&select=*&order=last_name,first_name'),
    healthFetch('health_dispensations?select=*&order=start_date.desc')
  ]);
  if(!healthSelectedClassId||!healthClasses.some(c=>c.id===healthSelectedClassId))healthSelectedClassId=healthClasses[0]?.id||null;
  renderHealthTab();
}
function renderHealthTab(){
 const host=document.getElementById('healthBody');if(!host)return;
 host.innerHTML=`<div class="healthHero"><div><span class="healthEyebrow">SUIVI DES ÉLÈVES</span><h1>Santé / Accident</h1><p>Dispenses, accidents et passages à l’infirmerie.</p></div><div class="healthHeroIcon">❤</div></div><div class="subtabbar healthTabs">${[['dispense','DISPENSE'],['accident','ACCIDENT'],['infirmerie','INFIRMERIE']].map(([id,label])=>`<button class="subtabbtn${healthMode===id?' active':''}" data-health-mode="${id}">${label}</button>`).join('')}</div><div id="healthModeBody"></div>`;
 host.querySelectorAll('[data-health-mode]').forEach(button=>button.onclick=()=>{healthMode=button.dataset.healthMode;renderHealthTab();});
 if(healthMode==='dispense')renderDispenseMode();else if(healthMode==='accident')renderAccidentMode();else document.getElementById('healthModeBody').innerHTML=`<div class="card healthEmpty"><h2>Infirmerie</h2><p>Cette rubrique est prête. Son formulaire sera ajouté à l’étape suivante.</p></div>`;
}
function renderDispenseMode(){
 const body=document.getElementById('healthModeBody'),classStudents=healthStudents.filter(s=>s.class_id===healthSelectedClassId),current=healthDispenses.filter(d=>d.class_id===healthSelectedClassId&&healthActive(d));
 const selected=healthStudents.find(s=>s.id===healthSelectedStudentId);
 body.innerHTML=`<div class="card healthControls"><label>Classe<select id="healthClassSelect">${healthClasses.map(c=>`<option value="${healthEsc(c.id)}" ${c.id===healthSelectedClassId?'selected':''}>${healthEsc(c.name)}</option>`).join('')}</select></label><span class="healthCount">${current.length} dispense(s) en cours</span></div>${healthClasses.length?`<div class="healthGrid"><section class="card"><h2>Élèves de la classe</h2><div class="healthStudentList">${classStudents.map(student=>{const active=healthDispenses.find(d=>d.student_id===student.id&&healthActive(d));return `<button class="healthStudent ${student.id===healthSelectedStudentId?'selected':''}" data-health-student="${healthEsc(student.id)}"><span>${healthEsc(student.last_name.toUpperCase())} ${healthEsc(student.first_name)}</span><small>${active?`Dispensé jusqu’au ${new Date(active.end_date+'T12:00:00').toLocaleDateString('fr-FR')}`:'Ajouter une dispense'}</small></button>`}).join('')||'<p class="muted">Aucun élève dans cette classe.</p>'}</div></section><section class="card" id="healthEditor">${selected&&selected.class_id===healthSelectedClassId?dispenseEditorHtml(selected):'<div class="healthEmpty"><h2>Nouvelle dispense</h2><p>Sélectionnez la ligne d’un élève.</p></div>'}</section></div><section class="card"><h2>Dispenses en cours</h2>${current.length?`<table><thead><tr><th>Élève</th><th>Début</th><th>Fin</th><th></th></tr></thead><tbody>${current.map(d=>{const s=healthStudents.find(x=>x.id===d.student_id);return `<tr><td>${healthEsc(s?`${s.last_name.toUpperCase()} ${s.first_name}`:'Élève')}</td><td>${healthEsc(d.start_date)}</td><td>${healthEsc(d.end_date)}</td><td><button class="secondary healthDelete" data-id="${d.id}">Supprimer</button></td></tr>`}).join('')}</tbody></table>`:'<p class="muted">Aucune dispense en cours.</p>'}</section>`:'<div class="card healthEmpty">Créez d’abord une classe.</div>'}`;
 const select=document.getElementById('healthClassSelect');if(select)select.onchange=()=>{healthSelectedClassId=select.value;healthSelectedStudentId=null;renderDispenseMode();};
 body.querySelectorAll('[data-health-student]').forEach(button=>button.onclick=()=>{healthSelectedStudentId=button.dataset.healthStudent;renderDispenseMode();});
 const form=document.getElementById('dispenseForm');if(form)form.onsubmit=saveDispense;
 body.querySelectorAll('.healthDelete').forEach(button=>button.onclick=()=>deleteDispense(button.dataset.id));
}
function dispenseEditorHtml(student){
 const history=healthDispenses.filter(d=>d.student_id===student.id);
 return `<h2>${healthEsc(student.last_name.toUpperCase())} ${healthEsc(student.first_name)}</h2><form id="dispenseForm"><label>Début de la dispense<input type="date" id="dispenseStart" value="${healthToday()}" required></label><label>Fin de la dispense<input type="date" id="dispenseEnd" value="${healthToday()}" required></label><button type="submit">Valider la dispense</button></form><h3>Historique de l’élève</h3>${history.length?history.map(d=>`<div class="healthHistory"><span>${healthEsc(d.start_date)} → ${healthEsc(d.end_date)}</span><strong>${healthActive(d)?'En cours':'Terminée'}</strong></div>`).join(''):'<p class="muted">Aucune dispense enregistrée.</p>'}`;
}
async function saveDispense(event){event.preventDefault();const start=document.getElementById('dispenseStart').value,end=document.getElementById('dispenseEnd').value;if(!start||!end||end<start){alert('La date de fin doit être postérieure ou égale à la date de début.');return;}const response=await apiFetch(`${SUPABASE_URL}/rest/v1/health_dispensations`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_id:session.user_id,class_id:healthSelectedClassId,student_id:healthSelectedStudentId,start_date:start,end_date:end})});const rows=await response.json();if(rows[0])healthDispenses.unshift(rows[0]);renderDispenseMode();}
async function deleteDispense(id){if(!confirm('Supprimer cette dispense ?'))return;await apiFetch(`${SUPABASE_URL}/rest/v1/health_dispensations?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});healthDispenses=healthDispenses.filter(d=>d.id!==id);renderDispenseMode();}
function openClassDispenses(classId){healthSelectedClassId=classId;healthMode='dispense';showTab('health');}

let accidentStep=0,accidentDraft={class_id:'',student_id:'',facts_nature:'',occurred_date:healthToday(),occurred_time:new Date().toTimeString().slice(0,5),damage_type:'',course_context:'EPS',course_other:'',time_context:'TEMPS_SCOLAIRE',activity_nature:'',responsible_name:'',diagram_data:'',witnesses:'',urgency_code:'VERT',decision_taken:''};
const accidentSteps=['Élève','Nature des faits','Date et heure','Dommage','Cours de','Moment des faits','Activité proposée','Responsable','Schéma','Témoins','Gestion de l’incident','Récapitulatif'];
function renderAccidentMode(){
 const host=document.getElementById('healthModeBody');
 if(!accidentDraft.responsible_name)accidentDraft.responsible_name=(typeof loadPrefs==='function'&&loadPrefs().teacherName)||session?.email?.split('@')[0]||'';
 host.innerHTML=`<section class="card accidentWizard"><div class="accidentProgress"><strong>Étape ${accidentStep+1}/${accidentSteps.length}</strong><span>${healthEsc(accidentSteps[accidentStep])}</span><progress value="${accidentStep+1}" max="${accidentSteps.length}"></progress></div><div id="accidentStepBody">${accidentStepHtml()}</div><div class="accidentNav">${accidentStep?'<button class="secondary" id="accidentPrev">← Précédent</button>':'<span></span>'}<button id="accidentNext">${accidentStep===accidentSteps.length-1?'Enregistrer et créer le PDF':'Suivant →'}</button></div></section>`;
 document.getElementById('accidentPrev')?.addEventListener('click',()=>{captureAccidentStep();accidentStep--;renderAccidentMode();});
 document.getElementById('accidentNext').onclick=async()=>{if(!captureAccidentStep(true))return;if(accidentStep<accidentSteps.length-1){accidentStep++;renderAccidentMode();}else await saveAccident();};
 if(accidentStep===0){const cs=document.getElementById('accClass');cs.onchange=()=>{accidentDraft.class_id=cs.value;accidentDraft.student_id='';renderAccidentMode();};}
 if(accidentStep===8)setupAccidentCanvas();
}
function accidentStepHtml(){
 const classStudents=healthStudents.filter(s=>s.class_id===(accidentDraft.class_id||healthClasses[0]?.id));
 const choices=(name,items,current)=>`<div class="accidentChoices">${items.map(([v,l,d])=>`<label class="accidentChoice ${current===v?'selected':''}"><input type="radio" name="${name}" value="${v}" ${current===v?'checked':''}><strong>${l}</strong>${d?`<small>${d}</small>`:''}</label>`).join('')}</div>`;
 switch(accidentStep){
  case 0: accidentDraft.class_id ||= healthClasses[0]?.id||''; return `<h2>Sélectionner l’élève</h2><label>Classe<select id="accClass">${healthClasses.map(c=>`<option value="${c.id}" ${c.id===accidentDraft.class_id?'selected':''}>${healthEsc(c.name)}</option>`).join('')}</select></label><div class="healthStudentList">${classStudents.map(s=>`<label class="healthStudent ${s.id===accidentDraft.student_id?'selected':''}"><input type="radio" name="accStudent" value="${s.id}" ${s.id===accidentDraft.student_id?'checked':''}><span><b>${healthEsc(s.last_name)} ${healthEsc(s.first_name)}</b> · ${healthEsc(s.birth_date||'Date de naissance non renseignée')} · ${healthEsc(healthClasses.find(c=>c.id===s.class_id)?.name||'')}</span></label>`).join('')}</div>`;
  case 1:return `<h2>Précisez la nature des faits</h2><textarea id="accFacts" rows="8" placeholder="Décrivez précisément et chronologiquement les faits…">${healthEsc(accidentDraft.facts_nature)}</textarea>`;
  case 2:return `<h2>Date et heure des faits</h2><div class="row"><label>Date<input id="accDate" type="date" value="${accidentDraft.occurred_date}"></label><label>Heure<input id="accTime" type="time" value="${accidentDraft.occurred_time}"></label></div>`;
  case 3:return `<h2>Dommage</h2>${choices('accDamage',[['MATERIEL','Matériel','Dégât concernant un objet ou une installation'],['PHYSIQUE','Physique','Blessure ou atteinte concernant une personne']],accidentDraft.damage_type)}`;
  case 4:return `<h2>Cours de</h2>${choices('accCourse',[['EPS','EPS','Cours d’éducation physique'],['AS','AS','Association sportive'],['AUTRE','Autre','À préciser ci-dessous']],accidentDraft.course_context)}<label>Précision si « Autre »<input id="accCourseOther" value="${healthEsc(accidentDraft.course_other)}"></label>`;
  case 5:return `<h2>Quand les faits ont-ils eu lieu ?</h2>${choices('accWhen',[['PERISCOLAIRE','Périscolaire',''],['SORTIE_SCOLAIRE','Sortie scolaire',''],['TEMPS_SCOLAIRE','Temps scolaire',''],['HORS_TEMPS_SCOLAIRE','Hors temps scolaire','']],accidentDraft.time_context)}`;
  case 6:return `<h2>Nature de l’activité proposée</h2><textarea id="accActivity" rows="6" placeholder="Activité, exercice, consigne donnée…">${healthEsc(accidentDraft.activity_nature)}</textarea>`;
  case 7:return `<h2>Personne responsable du cours</h2><label>Nom et prénom<input id="accResponsible" value="${healthEsc(accidentDraft.responsible_name)}"></label><p class="muted">Prérempli depuis le profil enseignant, mais modifiable pour cette déclaration.</p>`;
  case 8:return `<h2>Schéma de l’accident</h2><p class="muted">Dessinez au doigt ou à la souris. Vous pouvez aussi importer une image.</p><canvas id="accCanvas" width="760" height="360"></canvas><div class="row"><button type="button" class="secondary" id="accClear">Effacer</button><label class="secondary accidentImport">Importer une image<input id="accImage" type="file" accept="image/*" hidden></label></div>`;
  case 9:return `<h2>Témoin(s) éventuel(s)</h2><textarea id="accWitnesses" rows="6" placeholder="Nom, prénom, coordonnées ou précisions. Laissez vide s’il n’y en a pas.">${healthEsc(accidentDraft.witnesses)}</textarea>`;
  case 10:return `<h2>Gestion de l’incident</h2>${choices('accUrgency',[['VERT','Code vert — Sans urgence particulière','Situation maîtrisée ne nécessitant pas de prise en charge urgente.'],['ORANGE','Code orange — Urgence relative','Faits relativement urgents ou inquiétants.'],['ROUGE','Code rouge — Urgence absolue','Faits urgents ou graves.']],accidentDraft.urgency_code)}<label>Quelle décision a été prise ?<textarea id="accDecision" rows="5">${healthEsc(accidentDraft.decision_taken)}</textarea></label>`;
  default: {const s=healthStudents.find(x=>x.id===accidentDraft.student_id),c=healthClasses.find(x=>x.id===accidentDraft.class_id);return `<h2>Vérifiez la déclaration</h2><div class="accidentSummary"><b>Élève</b><span>${healthEsc(s?`${s.last_name} ${s.first_name}`:'')} · ${healthEsc(c?.name||'')}</span><b>Faits</b><span>${healthEsc(accidentDraft.facts_nature)}</span><b>Date</b><span>${accidentDraft.occurred_date} à ${accidentDraft.occurred_time}</span><b>Dommage</b><span>${accidentDraft.damage_type}</span><b>Cadre</b><span>${accidentDraft.course_context} · ${accidentDraft.time_context}</span><b>Activité</b><span>${healthEsc(accidentDraft.activity_nature)}</span><b>Responsable</b><span>${healthEsc(accidentDraft.responsible_name)}</span><b>Témoins</b><span>${healthEsc(accidentDraft.witnesses||'Aucun indiqué')}</span><b>Urgence</b><span>Code ${accidentDraft.urgency_code.toLowerCase()} — ${healthEsc(accidentDraft.decision_taken)}</span></div><p class="muted">Après enregistrement, le PDF pourra être téléchargé, enregistré ou partagé.</p>`;}
 }
}
function captureAccidentStep(validate=false){const val=id=>document.getElementById(id)?.value||'',radio=name=>document.querySelector(`input[name="${name}"]:checked`)?.value||'';if(accidentStep===0)accidentDraft.student_id=radio('accStudent');if(accidentStep===1)accidentDraft.facts_nature=val('accFacts').trim();if(accidentStep===2){accidentDraft.occurred_date=val('accDate');accidentDraft.occurred_time=val('accTime');}if(accidentStep===3)accidentDraft.damage_type=radio('accDamage');if(accidentStep===4){accidentDraft.course_context=radio('accCourse');accidentDraft.course_other=val('accCourseOther').trim();}if(accidentStep===5)accidentDraft.time_context=radio('accWhen');if(accidentStep===6)accidentDraft.activity_nature=val('accActivity').trim();if(accidentStep===7)accidentDraft.responsible_name=val('accResponsible').trim();if(accidentStep===8){const c=document.getElementById('accCanvas');if(c)accidentDraft.diagram_data=c.toDataURL('image/png');}if(accidentStep===9)accidentDraft.witnesses=val('accWitnesses').trim();if(accidentStep===10){accidentDraft.urgency_code=radio('accUrgency');accidentDraft.decision_taken=val('accDecision').trim();}const required=[accidentDraft.student_id,accidentDraft.facts_nature,accidentDraft.occurred_date,accidentDraft.occurred_time,accidentDraft.damage_type,accidentDraft.course_context,accidentDraft.time_context,accidentDraft.activity_nature,accidentDraft.responsible_name,accidentDraft.urgency_code,accidentDraft.decision_taken];if(validate&&accidentStep<11&&!required.slice(0,[1,2,4,5,7,8,8,9,9,9,11][accidentStep]).every(Boolean)){alert('Complétez cette étape avant de continuer.');return false;}if(validate&&accidentStep===4&&accidentDraft.course_context==='AUTRE'&&!accidentDraft.course_other){alert('Précisez le cours concerné.');return false;}return true;}
function setupAccidentCanvas(){const canvas=document.getElementById('accCanvas'),ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);if(accidentDraft.diagram_data){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,canvas.width,canvas.height);img.src=accidentDraft.diagram_data;}let drawing=false;const point=e=>{const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e;return [(p.clientX-r.left)*canvas.width/r.width,(p.clientY-r.top)*canvas.height/r.height]};canvas.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(...point(e));};canvas.onpointermove=e=>{if(!drawing)return;ctx.lineWidth=4;ctx.lineCap='round';ctx.strokeStyle='#173a57';ctx.lineTo(...point(e));ctx.stroke();};canvas.onpointerup=canvas.onpointerleave=()=>drawing=false;document.getElementById('accClear').onclick=()=>{ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);accidentDraft.diagram_data='';};document.getElementById('accImage').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);};img.src=reader.result;};reader.readAsDataURL(f);};}
async function saveAccident(){const payload={user_id:session.user_id,class_id:accidentDraft.class_id,student_id:accidentDraft.student_id,facts_nature:accidentDraft.facts_nature,occurred_at:`${accidentDraft.occurred_date}T${accidentDraft.occurred_time}:00`,damage_type:accidentDraft.damage_type,course_context:accidentDraft.course_context,course_other:accidentDraft.course_other||null,time_context:accidentDraft.time_context,activity_nature:accidentDraft.activity_nature,responsible_name:accidentDraft.responsible_name,diagram_data:accidentDraft.diagram_data||null,witnesses:accidentDraft.witnesses||null,urgency_code:accidentDraft.urgency_code,decision_taken:accidentDraft.decision_taken};const res=await apiFetch(`${SUPABASE_URL}/rest/v1/health_accidents`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});if(!res.ok){alert('Enregistrement impossible. Vérifiez que le nouveau SQL Santé a été exécuté.');return;}openAccidentPrintable();}
function openAccidentPrintable(){const s=healthStudents.find(x=>x.id===accidentDraft.student_id),c=healthClasses.find(x=>x.id===accidentDraft.class_id),w=open('','_blank');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Déclaration accident</title><style>body{font-family:Arial;padding:35px;color:#173a57}h1{color:#087dca}.line{padding:10px;border-bottom:1px solid #ccd9e2}b{display:inline-block;width:190px}img{max-width:100%;border:1px solid #ccd9e2}@media print{button{display:none}}</style></head><body><h1>Déclaration d’accident</h1><div class="line"><b>Élève</b>${healthEsc(s?`${s.last_name} ${s.first_name}`:'')} · ${healthEsc(c?.name||'')}</div><div class="line"><b>Date et heure</b>${accidentDraft.occurred_date} ${accidentDraft.occurred_time}</div><div class="line"><b>Nature des faits</b>${healthEsc(accidentDraft.facts_nature)}</div><div class="line"><b>Dommage</b>${accidentDraft.damage_type}</div><div class="line"><b>Cadre</b>${accidentDraft.course_context} · ${accidentDraft.time_context}</div><div class="line"><b>Activité</b>${healthEsc(accidentDraft.activity_nature)}</div><div class="line"><b>Responsable</b>${healthEsc(accidentDraft.responsible_name)}</div><div class="line"><b>Témoins</b>${healthEsc(accidentDraft.witnesses||'Aucun indiqué')}</div><div class="line"><b>Gestion</b>Code ${accidentDraft.urgency_code.toLowerCase()} — ${healthEsc(accidentDraft.decision_taken)}</div>${accidentDraft.diagram_data?`<h2>Schéma</h2><img src="${accidentDraft.diagram_data}">`:''}<p><button onclick="print()">Enregistrer / imprimer en PDF</button></p></body></html>`);w.document.close();accidentStep=0;accidentDraft={...accidentDraft,student_id:'',facts_nature:'',damage_type:'',activity_nature:'',diagram_data:'',witnesses:'',decision_taken:''};renderAccidentMode();}
