const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8894,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1400,height:900},serviceWorkers:'block'});
 await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
 await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});
 const page=await context.newPage();await page.goto('http://127.0.0.1:8894');await page.waitForTimeout(900);
 await page.evaluate(()=>showTab('unss'));await page.waitForTimeout(1000);
 await page.evaluate(()=>{unssSlots=[{id:'test1',activity_name:'Aquathlon',responsible_teacher:'Regnier',day_of_week:'mercredi',start_time:'13:00:00',end_time:'15:30:00'},{id:'test2',activity_name:'Natation',responsible_teacher:'M. Thooris',day_of_week:'lundi',start_time:'12:00',end_time:'13:00'}];unssStudents=[{id:'s1',last_name:'Martin',first_name:'Lina',division:'5-01'},{id:'s2',last_name:'Bernard',first_name:'Adam',division:'4-02'}];unssInscriptions=[{id:'m1',slot_id:'test1',student_id:'s1'},{id:'m2',slot_id:'test2',student_id:'s2'}];renderUnssSlotsTab();});
 const downloadBox=await page.locator('#unssSlotsDownloadBtn').boundingBox(),addBox=await page.locator('#unssSlotAddBtn').boundingBox();assert(downloadBox.x<addBox.x);
 await page.click('#unssSlotsDownloadBtn');assert.equal(await page.locator('[data-export-content]').count(),2);await page.click('[data-export-content="teachers"]');const downloading=page.waitForEvent('download');await page.click('[data-format="csv"]');const download=await downloading;assert.equal(download.suggestedFilename(),'creneaux-professeurs-aslvh.csv');
 const csv=fs.readFileSync(await download.path(),'utf8');assert(csv.includes('Aquathlon')&&csv.includes('M. Regnier')&&csv.includes('Mme Thooris')&&csv.includes('15h30'));assert.equal(csv.split('\r\n').length,3);
 await page.click('#unssSlotsDownloadBtn');await page.click('[data-export-content="teachers"]');const pdfDownload=page.waitForEvent('download');await page.click('[data-format="pdf"]');const pdf=await pdfDownload;assert.equal(pdf.suggestedFilename(),'creneaux-professeurs-aslvh.pdf');assert.equal(fs.readFileSync(await pdf.path()).subarray(0,8).toString('latin1'),'%PDF-1.4');
 await page.click('#unssSlotsDownloadBtn');await page.click('[data-export-content="students"]');const studentsDownload=page.waitForEvent('download');await page.click('[data-format="csv"]');const studentsCsvDownload=await studentsDownload;assert.equal(studentsCsvDownload.suggestedFilename(),'eleves-par-creneau-aslvh.csv');const studentsCsv=fs.readFileSync(await studentsCsvDownload.path(),'utf8');assert(studentsCsv.includes('Aquathlon')&&studentsCsv.includes('MARTIN')&&studentsCsv.includes('Lina')&&studentsCsv.includes('5-01'));
 await page.click('#unssSlotsDownloadBtn');await page.click('[data-export-content="students"]');const studentsPdfPromise=page.waitForEvent('download');await page.click('[data-format="pdf"]');const studentsPdf=await studentsPdfPromise;assert.equal(studentsPdf.suggestedFilename(),'eleves-par-creneau-aslvh.pdf');assert.equal(fs.readFileSync(await studentsPdf.path()).subarray(0,8).toString('latin1'),'%PDF-1.4');
 console.log('PASS teacher slots and registered students export directly to CSV or PDF');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
