const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8908,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage();page.setDefaultTimeout(5000);await page.goto('http://127.0.0.1:8908');await page.waitForTimeout(700);
 await page.evaluate(()=>{document.getElementById('mainView').style.display='block';document.getElementById('tab-programmation').style.display='block';planningMode='calendrier';renderPlanningTab();const day=new Date('2027-01-18T00:00:00').getTime();calendarEvents=[{id:'stage',label:'Stage découverte 3e',kind:'AUTRE',start_date_epoch_millis:day,end_date_epoch_millis:day,comment:''},{id:'parcoursup',label:'Ouverture Parcoursup',kind:'AUTRE',start_date_epoch_millis:day,end_date_epoch_millis:day,comment:''}];renderInstitutionCalendar();});
 const cell=page.locator('[data-cal-jour="2027-01-18"]');const title=await cell.getAttribute('title');assert.match(title,/Stage découverte 3e/);assert.match(title,/Ouverture Parcoursup/);await page.evaluate(()=>ouvrirJourCalendrier('2027-01-18'));assert.match(await page.locator('#planningPanel').innerText(),/2 événements/);assert.equal(await page.locator('#planningPanel [data-calendar-event]').count(),2);console.log('PASS multiple institution calendar events stay visible and editable');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
