const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8921,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage();page.on('dialog',d=>d.type()==='prompt'?d.accept('Groupe test'):d.accept());await page.goto('http://127.0.0.1:8921');await page.waitForTimeout(1000);
 await page.evaluate(()=>{globalThis.elevesActifsPourSeance=(id,list)=>list;showTab('outils');resetToolsWorkspace();openTool('climb-test')});await page.locator('#wfClass').selectOption('cl-3e6');await page.waitForTimeout(250);await page.locator('#wfAutoGroupSize').fill('3');await page.locator('#wfAutoGroups').tap();await page.waitForTimeout(100);
 assert.equal(await page.locator('.common-groups-ready').count(),1);assert.equal(await page.locator('[data-wf-assign]').count(),0);assert.equal(await page.locator('#wfEditGroups').count(),1);
 await page.locator('#wfEditGroups').tap();await page.waitForTimeout(80);await page.locator('[data-wf-assign]').nth(5).scrollIntoViewIfNeeded();const beforeScroll=await page.evaluate(()=>scrollY);await page.locator('[data-wf-assign]').nth(5).selectOption('');assert.equal(await page.evaluate(()=>scrollY),beforeScroll);
 await page.evaluate(()=>{epsOpenTest='ARRET_COURSE';openTool('tests')});await page.waitForTimeout(200);await page.locator('#toolClass').selectOption('cl-3e6');await page.waitForTimeout(200);await page.locator('#stopCreateGroup').tap();await page.waitForTimeout(80);assert.equal(await page.locator('.stop-group-editor').count(),1);assert.equal(await page.locator('.stop-pupils').count(),0);assert.equal(await page.locator('#stopSave').count(),0);await page.locator('[data-stop-pick-row]').first().tap();await page.locator('#stopApplyGroup').tap();await page.waitForTimeout(80);assert.equal(await page.locator('.stop-pupils').count(),1);assert.equal(await page.locator('#stopSave').count(),1);
 await page.evaluate(()=>{resetToolsWorkspace();openTool('multi-chrono')});await page.waitForTimeout(150);await page.locator('#modernClass').selectOption('cl-3e6');await page.waitForTimeout(180);await page.locator('#multiManageGroups').tap();assert.equal(await page.locator('.running-group-editor').count(),1);assert.equal(await page.locator('.multi-chrono-table').count(),0);await page.locator('[data-multi-group-student]').nth(0).check();await page.locator('[data-multi-group-student]').nth(1).check();await page.locator('#multiSaveGroup').tap();await page.waitForTimeout(80);assert.equal(await page.locator('.multi-chrono-table').count(),1);assert.equal(await page.locator('#multiManageGroups').innerText(),'Modifier les groupes');
 console.log('PASS groupes harmonisés : préparation repliée, défilement stable et outil isolé');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
