const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8898,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8898');await page.waitForTimeout(700);
 await page.evaluate(()=>{window.healthWrites=[];const originalApi=apiFetch;apiFetch=async(url,options)=>String(url).includes('/eps_schema_marks?')?new Response(JSON.stringify([{name:'applied'}])):originalApi(url,options);enregistrerLigne=async(table,row)=>{if(table==='health_dispensations')healthWrites.push(structuredClone(row));};});
 await page.evaluate(()=>ouvrirNouvelleDispense('cl-3e6',[{id:'new-student',last_name:'Durand',first_name:'Lina'}],'3e6'));await page.locator('#ficheEleve').selectOption('new-student');await page.locator('#ficheStart').fill('2026-09-28');await page.locator('#ficheEnd').fill('2026-10-10');await page.locator('#ficheForm button[type=submit]').click();await page.waitForTimeout(50);
 const created=await page.evaluate(()=>healthWrites[0]);assert.equal(created.student_last_name,'Durand');assert.equal(created.student_first_name,'Lina');assert.equal(created.class_name,'3e6');assert.equal(created.student_id,'new-student');
 await page.evaluate(()=>{healthWrites=[];const previous=lireTable;lireTable=async(table,url,options)=>table==='classes'?[{id:'cl-old',name:'5e2'}]:table==='students'?[{id:'st-old',class_id:'cl-old',last_name:'Martin',first_name:'Noa'}]:table==='health_dispensations'?[{id:'old-d',user_id:session.user_id,class_id:'cl-old',student_id:'st-old',start_date:'2026-09-01',end_date:'2026-12-01',deleted:false}]:previous(table,url,options);});await page.evaluate(()=>initHealthTab());await page.waitForTimeout(80);
 const repaired=await page.evaluate(()=>healthWrites.find(r=>r.id==='old-d'));assert(repaired);assert.equal(repaired.student_last_name,'Martin');assert.equal(repaired.student_first_name,'Noa');assert.equal(repaired.class_name,'5e2');assert.deepEqual(errors,[]);console.log('PASS shared dispense identity on class creation and automatic repair');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
