const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8897,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({serviceWorkers:'block',viewport:{width:1440,height:900}});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8897');await page.waitForTimeout(700);
 await page.evaluate(()=>{const original=lireTable;lireTable=async(table,url,options)=>table==='sport_installations'?[{id:'i1',name:'Gymnase'},{id:'i2',name:'Piscine'},{id:'i3',name:'Mur d’escalade'}]:table==='sport_installation_contacts'?[]:original(table,url,options);showTab('equipement')});await page.waitForTimeout(200);
 assert.equal(await page.locator('.installation-actions').count(),3);assert.equal(await page.locator('.installation-actions[open]').count(),0);assert.equal(await page.locator('.installation-card-actions>.ui-actions-menu').count(),0);
 const first=page.locator('.installation-actions').first(),second=page.locator('.installation-actions').nth(1);await first.locator('summary').click();assert.equal(await page.locator('.installation-actions[open]').count(),1);await second.locator('summary').click();await page.waitForTimeout(30);assert.equal(await page.locator('.installation-actions[open]').count(),1);assert(await second.getAttribute('open')!==null);
 const menu=second.locator('.ui-actions-menu'),box=await menu.boundingBox(),card=await second.locator('xpath=ancestor::div[@class="installation-card"]').boundingBox();assert(box.width<260);assert(box.x+box.width<=1440);assert(box.y>=card.y);
 await second.locator('summary').click();await page.waitForTimeout(30);assert.equal(await page.locator('.installation-actions[open]').count(),0);await page.setViewportSize({width:390,height:844});await page.locator('.installation-actions').nth(2).locator('summary').click();assert.equal(await page.locator('.installation-actions[open]').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);assert.deepEqual(errors,[]);console.log('PASS installation Actions closed by default, single compact menu, desktop and mobile');
 }finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
