const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8921,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8921');await page.waitForTimeout(700);
 await page.evaluate(async()=>{showTab('outils');await openTool('tests');window.providers={};const attach=EpsPronoteTools.attach;EpsPronoteTools.attach=(anchor,provider)=>{if(anchor)providers[anchor.id]=provider;attach(anchor,provider);};});
 await page.evaluate(()=>{toolPanel.innerHTML='<div id="epsTestBody"></div>';toolClassId='cl-3e6';epsTestPeriod=2;toolStudents=[{id:'a',first_name:'Lina',last_name:'TEST',sex:'FILLE'},{id:'b',first_name:'Adam',last_name:'TEST',sex:'GARCON'}];runningCount=6;runningDistance=250;runningDifficulty=0;runningGroups=[];runningActiveGroup=-1;runningValues.a=['100','100','100','100','100','100'];runningValues.b=['100','','','','',''];runningCreatedAt='2026-09-17';paintRunningSeriesTest({protocol:'Test'});});
 let data=await page.evaluate(()=>EpsPronoteTools.build(providers.runningExport()));assert.equal(data.title,'6 × 250 m · P2');assert.equal(data.date,'2026-09-17');assert.equal(data.rows.find(r=>r.firstName==='Lina').value,'18,33');assert.equal(data.rows.find(r=>r.firstName==='Adam').value,'');
 await page.locator('[data-pronote-tool]').click();assert.equal(await page.locator('dialog').count(),1);assert(await page.locator('dialog').evaluate(el=>el.getBoundingClientRect().width<=innerWidth));await page.locator('[data-close]').click();await page.locator('dialog').waitFor({state:'detached'});
 await page.evaluate(()=>{stopMode='note';stopAutoAppliedFor=toolClassId;stopCourseCounts.a=2;stopCourseCounts.b=0;paintStopCourseTest({protocol:'Test'});});data=await page.evaluate(()=>EpsPronoteTools.build(providers.stopExport()));assert.equal(data.rows.find(r=>r.firstName==='Lina').value,'19,5');assert.equal(data.rows.find(r=>r.firstName==='Adam').value,'20');await page.evaluate(()=>stopMode='couleur');assert.equal(await page.evaluate(()=>{try{EpsPronoteTools.build(providers.stopExport());return false}catch{return true}}),true);
 await page.evaluate(()=>renderClimbTestWeb({classId:'cl-3e6',period:2}));const student=await page.locator('[data-climb-field="progress"]').first().getAttribute('data-climb-student');await page.locator(`[data-climb-student="${student}"][data-climb-field="progress"]`).selectOption('0');await page.locator(`[data-climb-student="${student}"][data-climb-field="level"]`).selectOption('3A');for(const field of ['technique','belay'])await page.locator(`[data-climb-student="${student}"][data-climb-field="${field}"]`).fill('5');data=await page.evaluate(()=>EpsPronoteTools.build(providers.wfExport()));assert.equal(data.rows.filter(r=>r.value!=='').length,1);assert.equal(data.rows.find(r=>r.value!=='').value,'10,5');
 await page.evaluate(()=>renderConditionFitnessWeb());await page.locator('#fitnessClass').selectOption('cl-3e6');await page.locator('#fitnessGrouping').selectOption('alpha');await page.locator('#fitnessStart').click();const fitId=await page.locator('[data-fit-field]').first().getAttribute('data-fit-id');for(const [field,value] of Object.entries({pushups:'40',abs:'55',chair:'125',plank:'125',pullups:'15',flexibility:'5'}))await page.locator(`[data-fit-id="${fitId}"][data-fit-field="${field}"]`).fill(value);data=await page.evaluate(()=>EpsPronoteTools.build(providers.fitnessExport()));assert.equal(data.rows.filter(r=>r.value!=='').length,1);assert.equal(data.rows.find(r=>r.value!=='').value,'20');assert.deepEqual(errors,[]);console.log('PASS four real tool providers: 6x250 title/date/scale/incomplete, stops note/color, climbing four criteria, fitness six fields; mobile preview');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
