const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/Hp/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(p)&&fs.statSync(p).isDirectory())p=path.join(p,'index.html');try{res.setHeader('Content-Type',p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(p))}catch{res.statusCode=404;res.end()}});
(async()=>{await new Promise(r=>server.listen(8895,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
  const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block'});await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());await context.addInitScript({content:fs.readFileSync(path.join(root,'tests/faux-serveur.js'),'utf8')});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.type()==='prompt'?d.accept('Test audit'):d.accept());
  await page.goto('http://127.0.0.1:8895');await page.waitForTimeout(1000);
  await page.evaluate(()=>{
    window.auditDb={};
    const read=lireTable;
    lireTable=async function(table,url,options){
      if(['eps_saved_tool_works','eps_test_sessions','eps_test_results'].includes(table)){
        let rows=Object.values(auditDb[table]||{});
        const params=new URL('http://test/'+url).searchParams;
        for(const[k,v]of params)if(v.startsWith('eq.'))rows=rows.filter(r=>String(r[k])===v.slice(3));
        if(!options?.avecSupprimes)rows=rows.filter(r=>!r.deleted);
        return rows;
      }
      return read(table,url,options);
    };
    enregistrerLigne=async function(table,row){auditDb[table]??={};auditDb[table][row.id]=structuredClone(row)};
    showTab('outils');
  });
  const open=async id=>{await page.evaluate(id=>{resetToolsWorkspace();openTool(id)},id);await page.waitForTimeout(130)};
  for(const id of await page.evaluate(()=>EpsToolsCatalog.map(t=>t.id))){await open(id);assert(await page.locator('#toolPanel').innerText(),id);console.log('OPEN',id)}
  assert.deepEqual(errors,[]);
  const testKeys=await page.evaluate(()=>EpsTests.CATEGORIES.flatMap(c=>c.tests));for(const key of testKeys){await page.evaluate(()=>{epsOpenTest=null});await open('tests');await page.locator(`[data-eps-test="${key}"]`).click();await page.waitForTimeout(100);assert(await page.locator('#toolPanel h2').count());console.log('SUBTEST',key)}
  for(const [activity,id]of [['Gymnastique','gym-observation'],['Escalade','climb-observation']]){await page.evaluate(()=>resetToolsWorkspace());await page.locator(`[data-activity="${activity}"]`).click();assert.equal(await page.locator('[data-open-modern="observer"]').count(),0);await page.locator(`[data-open-modern="${id}"]`).click();await page.waitForTimeout(100);assert((await page.locator('#toolPanel').innerText()).includes('Observation '+activity));}
  // Exact user rubric, blank not confused with zero.
  await page.evaluate(()=>{const W=EpsToolWorkflow;for(const[,p]of W.PROGRESS)for(const[l,n]of W.LEVELS){if(W.climbScore({progress:String(p),level:l,technique:'5',belay:'5'})!==p+n+10)throw Error('barème')}if(W.climbScore({progress:'0',level:'3A',technique:'0',belay:'0'})!==0.5)throw Error('zero');if(W.climbScore({progress:'',level:'6A',technique:5,belay:5})!==null)throw Error('missing');if(W.climbScore({progress:5,level:'6A',technique:6,belay:5})!==null)throw Error('range')});
  await open('climb-test');await page.locator('#wfClass').selectOption('cl-3e6');await page.waitForTimeout(150);await page.locator('#wfPeriod').selectOption('3');await page.locator('#wfStart').click();
  const first=page.locator('[data-climb-field="progress"]').first();const student=await first.getAttribute('data-climb-student');await first.selectOption('0');await page.locator(`[data-climb-student="${student}"][data-climb-field="level"]`).selectOption('3A');for(const f of ['technique','belay'])await page.locator(`[data-climb-student="${student}"][data-climb-field="${f}"]`).fill('5');assert.equal(await page.locator(`[data-climb-total="${student}"]`).innerText(),'10,5 /20');
  await page.locator('#wfEditGroups').click();await page.locator('#wfAddGroup').click();await page.waitForTimeout(100);await page.locator('[data-wf-assign]').first().selectOption({index:1});await page.waitForTimeout(100);await page.locator('#wfFinishGroups').click();await page.locator('#wfSave').click();await page.waitForTimeout(120);
  const sessionId=await page.evaluate(()=>Object.keys(auditDb.eps_test_sessions)[0]);assert(sessionId);await open('score');await page.evaluate(id=>ouvrirSessionTestDepuisClasse(id,'cl-3e6',3,'Escalade /20'),sessionId);await page.waitForTimeout(100);assert.equal(await page.locator('#wfClass').inputValue(),'cl-3e6');assert.equal(await page.locator('#wfPeriod').inputValue(),'3');assert.equal(await page.locator(`[data-climb-total="${student}"]`).innerText(),'10,5 /20');await page.locator('#wfEditGroups').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-wf-group-name]').count(),1);await page.locator('#wfSave').click();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>Object.keys(auditDb.eps_test_sessions).length),1);console.log('PASS climbing rubric, group, save, reopen, update');
  for(const [id,fn,payload] of [['observer','renderObserverWeb',{sport:'Badminton',bareme:20,indicators:[['Service',1]],values:{}}],['tournament','renderTournamentWeb',{teams:'A\nB',scores:{0:[7,2]}}],['rotations','renderRotationsWeb',{stations:'A\nB',groups:2,step:1}],['acrosport','renderAcrosportWeb',{groups:[[student]],size:2}]]){
    await open(id);await page.evaluate(async({fn,payload})=>window[fn]({id:'record-'+fn,title:'Audit',classId:'cl-3e6',period:3,payload}),{fn,payload});await page.waitForTimeout(100);assert.equal(await page.locator(id==='observer'?'#modernClass':'#wfClass').inputValue(),'cl-3e6');assert.equal(await page.locator(id==='observer'?'#modernPeriod':'#wfPeriod').inputValue(),'3');console.log('PASS context',id)
  }
  await open('tournament');await page.locator('#tourMatches input').first().fill('7');await page.locator('#tourBuild').click();await page.waitForTimeout(80);assert.equal(await page.locator('#tourMatches input').first().inputValue(),'7');const dl=page.waitForEvent('download');await page.locator('#wfExport').click();const download=await dl;assert(fs.readFileSync(await download.path(),'utf8').includes('"7"'));console.log('PASS tournament preserve and export scores');
  for(const [id,selector,value]of [['swim','[data-swim]',true],['aptitudes','[data-apt]','5.4'],['speed','#speedDistance','42'],['impacts','#impactCanvas',null]]){
    await open(id);await page.locator('#toolClass').selectOption('cl-3e6');await page.waitForTimeout(100);await page.locator('#wfPeriod').selectOption('3');await page.locator('#wfStart').click();if(value===true)await page.locator(selector).first().check();else if(value===null)await page.locator(selector).click({position:{x:80,y:80}});else{await page.locator(selector).first().fill(value);await page.locator(selector).first().dispatchEvent('change')}await page.locator('#wfSave').click();await page.waitForTimeout(100);
    if(id==='aptitudes'){
      const saved=await page.evaluate(()=>Object.values(auditDb.eps_test_sessions).find(s=>s.test_name==='Aptitudes physiques 6e'));
      assert(saved,'aptitudes in class Tests EPS');assert.equal(saved.period_number,3);
      assert.equal(await page.evaluate(id=>Object.values(auditDb.eps_test_results).filter(r=>r.session_id===id).length,saved.id),1);
      await open('score');await page.evaluate(id=>ouvrirSessionTestDepuisClasse(id,'cl-3e6',3,'Aptitudes physiques 6e'),saved.id);
      assert.equal(await page.locator('[data-apt]').first().inputValue(),value);
    }else{
      const saved=await page.evaluate(id=>Object.values(auditDb.eps_saved_tool_works).find(w=>w.type===id),id);assert(saved,id);assert.equal(saved.period_number,3);await open('score');await page.evaluate(async saved=>{toolPanel=document.getElementById('toolPanel');await renderPersistedTool(saved.type,{id:saved.id,classId:saved.class_id,period:saved.period_number,title:saved.title,payload:JSON.parse(saved.payload)})},saved);if(value===true)assert(await page.locator(selector).first().isChecked());else if(value!==null)assert.equal(await page.locator(selector).first().inputValue(),value);else assert((await page.locator('#impactCount').innerText()).startsWith('1'));
    }
    console.log('PASS durable roundtrip',id)
  }
  await page.evaluate(()=>{auditDb.eps_saved_tool_works['legacy-apt']={id:'legacy-apt',user_id:session.user_id,type:'aptitudes',title:'Ancien test 6e',class_id:'cl-3e6',period_number:2,created_at:Date.now()-1000,deleted:false,payload:JSON.stringify({values:{'el-0':{sprint:'5.5',endurance:'4',jump:'145'}},workflow:{groups:[],assignments:{}}})}});
  assert.equal(await page.evaluate(()=>EpsAptitudes.migrateLegacy('cl-3e6')),1);
  assert.equal(await page.evaluate(()=>EpsAptitudes.migrateLegacy('cl-3e6')),0);
  assert.equal(await page.evaluate(()=>auditDb.eps_test_sessions['legacy-apt'].period_number),2);
  assert.equal(await page.evaluate(()=>auditDb.eps_saved_tool_works['legacy-apt'].deleted),false);
  await page.evaluate(()=>{auditDb.eps_test_sessions['legacy-apt'].deleted=true});
  assert.equal(await page.evaluate(()=>EpsAptitudes.migrateLegacy('cl-3e6')),0,'un test supprimé ne doit pas être recréé depuis Travaux');
  assert.equal(await page.evaluate(()=>auditDb.eps_test_sessions['legacy-apt'].deleted),true);
  console.log('PASS anciens tests 6e visibles dans la classe sans supprimer la sauvegarde originale');
  await open('tests');await page.locator('#toolClass').selectOption('cl-3e6');await page.waitForTimeout(80);await page.locator('[data-eps-test="ARRET_COURSE"]').click();await page.waitForTimeout(150);assert.equal(await page.locator('.stop-pupils').isVisible(),false);assert.equal(await page.locator('#stopCreateGroup').isVisible(),true);await page.locator('#epsBegin').click();assert.equal(await page.locator('.stop-pupils').isVisible(),true);assert.equal(await page.locator('#stopCreateGroup').isVisible(),false);await page.locator('#epsEditPreparation').click();assert.equal(await page.locator('.stop-pupils').isVisible(),false);console.log('PASS stop-course setup and results separated');
  await open('teams');await page.locator('#twFree').fill('Alex;F\nSam;M\nJo;F\nMax;M');await page.locator('#twFree').dispatchEvent('change');await page.locator('#twMode').selectOption('MIXTE_EQUILIBRE');await page.locator('#twGenerate').click();assert.equal(await page.locator('[data-team-move]').count(),4);assert.equal(await page.locator('#twError').innerText(),'');await page.evaluate(()=>{const list=Array.from({length:8},(_,i)=>({id:String(i),last_name:'Name'+i,sex:i<4?'F':'M'}));const ratings=Object.fromEntries(list.map((s,i)=>[s.id,i]));const homogeneous=distributeToolTeams(list,2,'HOMOGENE',ratings);if(homogeneous[0].some(s=>+s.id<4))throw Error('levels ignored');const mixed=distributeToolTeams(list,2,'MIXTE_EQUILIBRE');if(mixed.some(g=>g.filter(s=>s.sex==='F').length!==2))throw Error('mixity')});console.log('PASS teams free, levels and mixity');
  await page.evaluate(()=>{epsOpenTest=null;drawEpsTests()});await page.locator('#toolClass').selectOption('cl-3e6');await page.waitForTimeout(80);await page.locator('[data-eps-test="SPRINT_30"]').click();await page.waitForTimeout(150);await page.locator('#genericGroupCount').selectOption('2');await page.locator('[data-generic-student-group]:visible').first().selectOption('2');await page.locator('#epsBegin').click();await page.locator('[data-eps-input]').first().fill('5');assert.equal(await page.locator('.eps-test-context').isVisible(),false);await page.locator('#epsEditPreparation').click();assert.equal(await page.locator('[data-eps-input]').first().isVisible(),false);await page.locator('#epsBegin').click();assert.equal(await page.locator('[data-eps-input]').first().inputValue(),'5');await page.locator('#epsSaveBtn').click();await page.waitForTimeout(150);const sprintId=await page.evaluate(()=>Object.values(auditDb.eps_test_sessions).find(s=>s.test_name==='Sprint 30 metres').id);await open('score');await page.evaluate(id=>ouvrirSessionTestDepuisClasse(id,'cl-3e6',1,'Sprint 30 metres'),sprintId);await page.waitForTimeout(150);assert.equal(await page.locator('.eps-test-context').isVisible(),false);assert.equal(await page.locator('[data-eps-input]').first().inputValue(),'5');console.log('PASS generic groups durable and setup hidden');
  await open('vma');await page.waitForTimeout(100);await page.locator('#vmaPeriod').selectOption('3');await page.locator('#wfAddGroup').click();await page.waitForTimeout(100);await page.locator('[data-wf-group-name]').fill('Endurance');await page.locator('[data-wf-group-name]').dispatchEvent('change');await page.waitForTimeout(100);await page.locator('#vmaSaveBtn').click();await page.waitForTimeout(150);const vmaId=await page.evaluate(()=>Object.values(auditDb.eps_test_sessions).find(s=>s.test_name.startsWith('Test VMA')).id);await page.evaluate(id=>openVmaSession(id),vmaId);await page.waitForTimeout(150);assert.equal(await page.locator('#vmaPeriod').inputValue(),'3');await page.locator('#wfEditGroups').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-wf-group-name]').inputValue(),'Endurance');console.log('PASS VMA group and period');
  await open('gym-observation');await page.locator('#gymObsClass').selectOption('cl-3e6');await page.waitForTimeout(100);await page.locator('#gymObsStart').click();await page.waitForTimeout(100);await page.locator('#wfAddGroup').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-wf-group-name]').count(),1);await page.locator('#gymObsSave').click();await page.waitForTimeout(150);const gymId=await page.evaluate(()=>Object.values(auditDb.eps_test_sessions).find(s=>s.test_name==='Observation Gymnastique').id);await page.evaluate(id=>ouvrirSessionTestDepuisClasse(id,'cl-3e6',1,'Observation Gymnastique'),gymId);await page.waitForTimeout(150);await page.locator('#wfEditGroups').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-wf-group-name]').count(),1);console.log('PASS Gym specific model and groups');
  await open('climb-test');await page.locator('#wfClass').selectOption('cl-3e6');await page.waitForTimeout(120);await page.locator('#wfStart').click();await page.screenshot({path:path.join(root,'../output/climbing-desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'../output/climbing-mobile.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
  const stickyBefore=await page.locator('.climb-worksheet td').first().boundingBox();await page.locator('.climb-worksheet .fitness-table-wrap').evaluate(el=>el.scrollLeft=500);const stickyAfter=await page.locator('.climb-worksheet td').first().boundingBox();assert(Math.abs(stickyAfter.x-stickyBefore.x)<2,'student names stay visible');
  await page.evaluate(()=>{window.realAuditWrite=enregistrerLigne;enregistrerLigne=async()=>{throw Error('Panne simulée')}});await page.locator('#wfSave').click();await page.waitForTimeout(100);assert((await page.locator('#wfStatus').innerText()).includes('impossible'));assert(await page.locator('#wfSave').isEnabled());await page.evaluate(()=>enregistrerLigne=realAuditWrite);assert.deepEqual(errors,[]);console.log('ALL PASS');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
